/*
 * Second half of `npm run build`: builds the admin panel into dist/<ADMIN_PATH>/ and appends its
 * Cloudflare Pages rules to dist/_redirects and dist/_headers. Those are generated files (dist/ is
 * git-ignored) and Cloudflare never serves them to visitors.
 *
 * If ADMIN_PATH is missing or weak, no admin panel is built at all (never a default like /admin):
 * the public site still deploys, and a warning is printed.
 */
import { appendFileSync, existsSync } from 'node:fs'
import { fileURLToPath, URL } from 'node:url'
import { build, loadEnv } from 'vite'
import { checkAdminPath, redact } from './path-rules.ts'

const projectRoot = fileURLToPath(new URL('..', import.meta.url))
const dist = fileURLToPath(new URL('../dist/', import.meta.url))
const env = loadEnv('production', projectRoot, '')
const check = checkAdminPath(env.ADMIN_PATH)

if (!check.ok) {
  console.warn(
    [
      '',
      '!!! ADMIN PANEL NOT BUILT: ' + check.reason,
      '    The public site was built without any admin panel.',
      '    Set a strong ADMIN_PATH (10+ characters: letters, digits, "-" or "_"; no guessable words)',
      '    in .env.local (this computer) or in the Cloudflare Pages environment variables, then build again.',
      '',
    ].join('\n'),
  )
  process.exit(0)
}

const path = check.path

function fail(message: string): never {
  console.error(`\nAdmin panel build failed: ${redact(message, path)}\n`)
  process.exit(1)
}

if (!existsSync(`${dist}index.html`)) fail('run the public build first (npm run build).')
// dist/ was just emptied by the public build, so anything here belongs to the public site.
if (existsSync(`${dist}${path}`) || existsSync(`${dist}${path}.html`)) fail('ADMIN_PATH clashes with a public page or folder.')

try {
  await build({ configFile: fileURLToPath(new URL('./vite.config.ts', import.meta.url)), mode: 'production' })
} catch (error) {
  fail(error instanceof Error ? (error.stack ?? error.message) : String(error))
}

// Deep links (/<path>/security, …) serve the panel's index.html. Cloudflare applies _redirects even
// when a file exists, so the rule matches one segment only and never catches /<path>/assets/….
appendFileSync(
  `${dist}_redirects`,
  ['', '# Admin panel (generated by admin/build.ts)', `/${path}/:page  /${path}/  200`, ''].join('\n'),
)

// The panel only talks to its own origin and the Supabase project; the browser blocks anything else.
const supabase = env.VITE_SUPABASE_URL ? new URL(env.VITE_SUPABASE_URL).origin : ''
const csp = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  // Supabase storage serves the uploaded photos; blob: is the local preview before upload.
  `img-src 'self' data: blob: ${supabase}`.trim(),
  `connect-src 'self' ${supabase}`.trim(),
  "object-src 'none'",
  "base-uri 'none'",
  "form-action 'none'",
  "frame-ancestors 'none'",
].join('; ')
const rules = [
  'X-Robots-Tag: noindex, nofollow, noarchive',
  '! Referrer-Policy', // drop the site-wide value before setting the stricter one
  'Referrer-Policy: no-referrer',
  'Cache-Control: no-store',
  `Content-Security-Policy: ${csp}`,
]
appendFileSync(
  `${dist}_headers`,
  ['', '# Admin panel (generated by admin/build.ts)', ...[`/${path}`, `/${path}/*`].flatMap((p) => [p, ...rules.map((r) => `  ${r}`)]), ''].join(
    '\n',
  ),
)

console.log('\nAdmin panel built into dist/<ADMIN_PATH>/, with its _redirects and _headers rules.\n')
