/**
 * Writes supabase/seed.sql from the TypeScript seed in src/content/seed/.
 *
 *   npm run seed:sql
 *
 * The TypeScript files are the single source of truth (they carry the `// review-ar` marks);
 * never edit seed.sql by hand. Every insert is "on conflict do nothing", so running the seed
 * again never overwrites changes the owner made in the admin panel.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { seedCategories, seedProductCategories, seedServices, seedSettings } from '../src/content/seed'

const OUT = fileURLToPath(new URL('../supabase/seed.sql', import.meta.url))

const str = (v: string | null | undefined) => (v === null || v === undefined ? 'null' : `'${v.replaceAll("'", "''")}'`)
const bool = (v: boolean) => (v ? 'true' : 'false')
const int = (v: number) => String(Math.trunc(v))
const json = (v: unknown) => `${str(JSON.stringify(v))}::jsonb`
const textArray = (v: string[]) => (v.length === 0 ? `'{}'::text[]` : `array[${v.map(str).join(', ')}]::text[]`)

function insert(table: string, row: Record<string, string>, conflict: string) {
  const cols = Object.keys(row)
  return [
    `insert into public.${table} (${cols.join(', ')})`,
    `values (\n  ${cols.map((c) => row[c]).join(',\n  ')}\n)`,
    `on conflict ${conflict} do nothing;`,
  ].join('\n')
}

const parts: string[] = [
  '-- GENERATED by scripts/generate-seed-sql.ts from src/content/seed/*.ts — do not edit by hand.\n' +
    '-- Safe to re-run: existing rows are left untouched.',
  'begin;',
  '-- Settings',
  ...Object.entries(seedSettings).map(([key, value]) => insert('settings', { key: str(key), value: json(value) }, '(key)')),
  '-- Service categories',
  ...seedCategories.map((c) =>
    insert(
      'categories',
      {
        slug: str(c.slug),
        name_ar: str(c.name_ar),
        name_en: str(c.name_en),
        headline_ar: str(c.headline_ar),
        headline_en: str(c.headline_en),
        intro_ar: str(c.intro_ar),
        intro_en: str(c.intro_en),
        meta_description_ar: str(c.meta_description_ar),
        meta_description_en: str(c.meta_description_en),
        covers_ar: textArray(c.covers_ar),
        covers_en: textArray(c.covers_en),
        faq: json(c.faq),
        icon: str(c.icon),
        image_url: str(c.image_url),
        wa_message_ar: str(c.wa_message_ar),
        wa_message_en: str(c.wa_message_en),
        sort_order: int(c.sort_order),
        is_active: bool(c.is_active),
        is_primary: bool(c.is_primary),
      },
      '(slug)',
    ),
  ),
  '-- Services',
  ...seedServices.map((s) =>
    insert(
      'services',
      {
        category_id: `(select id from public.categories where slug = ${str(s.category)})`,
        slug: str(s.slug),
        name_ar: str(s.name_ar),
        name_en: str(s.name_en),
        short_ar: str(s.short_ar),
        short_en: str(s.short_en),
        body_ar: str(s.body_ar),
        body_en: str(s.body_en),
        includes_ar: textArray(s.includes_ar),
        includes_en: textArray(s.includes_en),
        excludes_ar: textArray(s.excludes_ar),
        excludes_en: textArray(s.excludes_en),
        options_ar: textArray(s.options_ar),
        options_en: textArray(s.options_en),
        parts_ar: textArray(s.parts_ar),
        parts_en: textArray(s.parts_en),
        parts_in_stock: bool(s.parts_in_stock),
        wa_message_ar: str(s.wa_message_ar),
        wa_message_en: str(s.wa_message_en),
        image_url: str(s.image_url),
        faq: json(s.faq),
        has_detail_page: bool(s.has_detail_page),
        featured: bool(s.featured),
        sort_order: int(s.sort_order),
        is_active: bool(s.is_active),
      },
      '(category_id, slug)',
    ),
  ),
  '-- Product categories (items are added from the admin panel)',
  ...seedProductCategories.map((c) =>
    insert(
      'product_categories',
      {
        slug: str(c.slug),
        name_ar: str(c.name_ar),
        name_en: str(c.name_en),
        sort_order: int(c.sort_order),
        is_active: bool(c.is_active),
      },
      '(slug)',
    ),
  ),
  'commit;',
]

writeFileSync(OUT, `${parts.join('\n\n')}\n`, 'utf8')
console.log(
  `Wrote ${OUT}: ${Object.keys(seedSettings).length} settings, ${seedCategories.length} categories, ` +
    `${seedServices.length} services (${seedServices.filter((s) => s.has_detail_page).length} with detail pages), ` +
    `${seedProductCategories.length} product categories.`,
)
